package com.adnostr.app;

import android.os.Build;
import android.os.Bundle;
import android.text.Html;
import android.text.Spanned;
import android.util.Log;
import android.view.View;
import android.view.WindowManager;

import androidx.appcompat.app.AppCompatActivity;
import androidx.core.content.ContextCompat;

import com.adnostr.app.databinding.ActivityDescriptionDetailsBinding;

/**
 * Full-Screen Description Viewer.
 * FEATURE: Renders the total professionally formatted ad description.
 * FEATURE: Implements HTML-to-Span conversion for rich text display.
 * FEATURE: Supports legacy and modern Android HTML rendering modes.
 * FEATURE: Provides an immersive, distraction-free reading environment.
 * 
 * THEME ENGINE UPDATE:
 * - Dynamic Status Bar: Adapts to Day/Night mode while preserving "Premium Viewer" aesthetics.
 */
public class DescriptionDetailsActivity extends AppCompatActivity {

    private static final String TAG = "AdNostr_DescDetails";
    private ActivityDescriptionDetailsBinding binding;
    private AdNostrDatabaseHelper db;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        db = AdNostrDatabaseHelper.getInstance(this);

        // 1. Immersive UI Flags (Matches the premium feel of the Ad Popup)
        getWindow().addFlags(WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS);
        
        // =========================================================================
        // THEME ENGINE: Conditional Status Bar Logic
        // =========================================================================
        if (db.isDayMode()) {
            getWindow().setStatusBarColor(ContextCompat.getColor(this, R.color.white));
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
                getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);
            }
        } else {
            getWindow().setStatusBarColor(android.graphics.Color.parseColor("#1E1E1E"));
        }

        binding = ActivityDescriptionDetailsBinding.inflate(getLayoutInflater());
        setContentView(binding.getRoot());

        // 2. Retrieve the formatted HTML string from the Intent
        String fullHtml = getIntent().getStringExtra("FULL_DESCRIPTION_HTML");

        if (fullHtml != null && !fullHtml.isEmpty()) {
            renderFormattedDescription(fullHtml);
        } else {
            binding.tvFullDescription.setText("No additional details provided for this ad.");
            Log.w(TAG, "Activity launched but FULL_DESCRIPTION_HTML was null or empty.");
        }

        // 3. Setup Navigation Logic
        binding.btnCloseDetails.setOnClickListener(v -> finish());
    }

    /**
     * Converts raw HTML string into a Spanned object for the TextView.
     * Uses FROM_HTML_MODE_LEGACY for maximum compatibility with various HTML tags
     * generated by the RichTextEditorActivity.
     */
    private void renderFormattedDescription(String htmlContent) {
        try {
            Spanned formattedText;

            if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.N) {
                // Modern API (Android 7.0+)
                formattedText = Html.fromHtml(htmlContent, Html.FROM_HTML_MODE_LEGACY);
            } else {
                // Legacy API
                formattedText = Html.fromHtml(htmlContent);
            }

            // Apply to the UI
            binding.tvFullDescription.setText(formattedText);
            
            Log.i(TAG, "Successfully rendered Rich Text description expansion.");

        } catch (Exception e) {
            Log.e(TAG, "HTML Rendering Failure: " + e.getMessage());
            // Fallback: Show raw text if rendering engine fails
            binding.tvFullDescription.setText(htmlContent);
        }
    }

    /**
     * Standard cleanup to prevent memory leaks with ViewBinding.
     */
    @Override
    protected void onDestroy() {
        super.onDestroy();
        binding = null;
    }
}